### ISSUE TITLE
The recordPosition keep running after 5 times

### ISSUE THREAD

**Issue by YibiaoLiang** [QishengLi/virtual_chinrest#2]
Hi, I find out that the recordPosition function keeps running after the "counter" is 0. That is， even the ball is not moving, but if you press the space, it will record it and recalculate the viewing distance. This may affect the result if participants make mistakes. By the way, using blindspot to calculate viewing distance, GENIUS.

**Comment by QishengLi** [comment]
Thanks for your interest in Virtual Chinrest and for catching the bug! 

I just added a simple function to deactivate the space key after people press it 5 times. Let me know if you have any other questions!
