### ISSUE TITLE
bug in viewing distance calculation?

### ISSUE THREAD

**Issue by pjkohler** [QishengLi/virtual_chinrest#3]
Hi Qisheng

When you compute the viewing distance:

https://github.com/QishengLi/virtual_chinrest/blob/f7adb2dc27fef322ea8a680872f08ac3a1eee52f/src/virtual_chinrest.js#L107

should that not be

var viewDistance = ball_sqr_distance / Math.tan(Math.radians(angle));

according to Equation 2 in your paper?

Unless I am missing something your code would slightly overestimate the viewing distance (by ~2%) given the angle and measured distance between ball and fixation.

Best,

Peter

**Comment by QishengLi** [comment]
Thank you very much for catching this bug, Peter! I have fixed it in the [recent commit](https://github.com/QishengLi/virtual_chinrest/commit/764b9e0b846b3601a985cb22ecd5b33110e49ff6).

Best,
Qisheng

**Comment by pjkohler** [comment]
great, thanks!
