### ISSUE TITLE
Why isn't the black square located at the horizontal center of the screen?

### ISSUE THREAD

**Issue by Brice-xCIT** [QishengLi/virtual_chinrest#4]
Hello and thank you for this work. 

Reading through your paper, it seems like the method relies on measuring the distance between the blind spot and the _center of display_, however the fixation black square never really is at the center of the display's X axis. Instead its position seems to vary with the `px2mm` measurement of card size. 

I'm curious whether this is intentional, and whether the viewing distance measurement that results from this non-central position of the black square is equivalent to what it would be if the black square was at the center.

**Comment by QishengLi** [comment]
Hi! Thanks for your question.

Yes, ideally, the fixation should be at the center of the screen. However, it's not always possible depending on the size/resolution of your screen (your window might be too small so the red ball would never disappear from your sight if placing the fixation square at the center of the screen). I think the error of the measurement will be insignificant in this case. But keep the fixation in the center, if you can!

I hope it helps!

**Comment by Brice-xCIT** [comment]
Thank you for your response! It should be fine this way, then.
